name: FIRST_WORKFLOW
on:
  workflow_dispatch:
    inputs:
      pxc_version:
        description: "pxc version"
        required: false
      pxc_glibc:
        description: "pxc glibc version"
        required: true
      pmm_image:
        description: "pmm_image"
        required: false
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  FIRST_WORKFLOW:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      PXC_VERSION: ${{ github.event.inputs.pxc_version || '8.0.33-25.1' }}
      PXC_GLIBC: ${{ github.event.inputs.pxc_glibc || '2.17' }}
      PMM_IMAGE: ${{ github.event.inputs.pmm_image || 'perconalab/pmm-server:dev-latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Run basic command
      run: echo "First Workflow"
    - name: Test 2nd repo trigger
      run: |
        curl -X POST https://api.github.com/repos/panchal-yash/repo2/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.SECOND_REPO_PAT }} \
        --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
